spring:
  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: false
    properties:
      hibernate.jdbc.time_zone: UTC
  flyway:
    enabled: false
    locations: classpath:db/migration
  mail:
    host: smtp.gmail.com
    port: 587
    username: ${SPRING_MAIL_USERNAME}
    password: ${SPRING_MAIL_PASSWORD}
    properties:
      mail.smtp.auth: true
      mail.smtp.starttls.enable: true

app:
  polygon:
    baseUrl: https://api.polygon.io
    apiKey: ${POLYGON_API_KEY}

  alpaca:
    trading:
      baseUrl: https://paper-api.alpaca.markets
      keyId: ${ALPACA_KEY_ID}
      secretKey: ${ALPACA_SECRET_KEY}
      accountId: ${ALPACA_ACCOUNT_ID}
    data:
      baseUrl: https://data.alpaca.markets
      keyId: ${ALPACA_KEY_ID}
      secretKey: ${ALPACA_SECRET_KEY}
       
  notification:
    slack:
      webhook-url: ${SLACK_WEBHOOK_URL}
    email:
      to: ${MAIL_TO}
      from: ${MAIL_FROM}

logging:
  level:
    com.stock.demo: INFO
    org.springframework: INFO

management:
  endpoints:
    web:
      exposure:
        include: health,info
